### ISSUE TITLE
AttributeError: 'module' object has no attribute 'allure'

### ISSUE THREAD

**Issue by sobolewska** [allure-framework/allure-nose#11]
My tests are organized to extend unittest.TestCase, so my tests classes are like this:

```
class TestLogin(MySetup):
    def test_LogIn_1(self):
```

I can run such tests both from debug (for example right click and select debug 'test_LogIn_1') and from command line with nose

i added allure decorators

```
import nose

class TestLogin(MySetup):
    @nose.allure.feature('Logging in')
    @nose.allure.story('As admin I can login in with valid data')
    def test_LogIn_1(self):
```

i can run such tests only from command line with nose and --with-allure, but when i try to debug, im getting error:

```
AttributeError: 'module' object has no attribute 'allure'
```

i checked it, and indeed there is no nose.allure, only \site-packages\nose_allure, \site-packages\allure, but no allure in site-packages\nose

now, to be able to debug, i need to comment out any allure decorator, which is unacceptable

_edit_

I'm able to workaround with some ugly hack. In file were class MySetup is, i added:

```
try:
    feature = nose.allure.feature
    story = nose.allure.story
    issue = nose.allure.issue
except (AttributeError, ImportError):
    def options(value):
        def decorator(target):
            log.debug(value)
            return target
        return decorator
    feature = options
    story = options
    issue = options
```

then in my tests files i import

```
from my_setup import MySetup, feature, story
```

and i decorate tests with @feature and @story, instead of @nose.allure.feature and @nose.allure.story

**Comment by brevno** [comment]
+1 to this issue:
`pip install nose `nose-allure-plugin`
`python -c 'import nose; print nose.allure.feature'`

Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'allure'

Any wrong steps duiring installation?

**Comment by vlipin-rabweb** [comment]
+1, got the same issue, who could help to resolve? Or what is the correct way of annotations/decorators usage?

**Comment by brevno** [comment]
I found out that when module is run not by python interpreter directly, but from 'nosetests' script, the impots seem to work fine. So you can use @sobolewska 's hack to support both launch modes.

**Comment by campside** [comment]
I had this problem on windows, but on mac everything worked fine, I manually installed the following requirements: 
`attrs==17.4.0
enum34==1.1.6
lxml==4.1.1
namedlist==1.7
pluggy==0.6.0
py==1.5.2
pytest==3.3.2
pytest-allure-adaptor==1.7.10
selenium==3.8.1
six==1.11.0
`
and everything went fine on windows too
