### ISSUE TITLE
question: how to get the html report 

### ISSUE THREAD

**Issue by p00j4** [allure-framework/allure-nose#14]
have installed the "nose-allure-plugin" adapter & able to generate the xml using " --with-allure" flag but what plugin dependency is required to get the allure html report?
do I need  write my own xml->html parser ? 
with TestNg, it is direct in [this example](https://github.com/allure-examples/allure-testng-example) but does same exists for nose ?

**Comment by kevanescence** [comment]
Hi,
I personally use the [allure command](http://wiki.qatools.ru/display/AL/Allure+Commandline). You also have several plugins for some continuous integration tools. (eg Jenkins) 
More details here [https://github.com/allure-framework/allure-core/wiki](https://github.com/allure-framework/allure-core/wiki)

**Comment by vlipin-rabweb** [comment]
@p00j4 Install allure command line and than use commands 
  -> allure generate ./<folder_with_your_xunit> (after this command in your Project root allure-report folder should be generated)
  -> allure report open

**Comment by jayeshd7** [comment]
there are very simple way to genrated reports via allure.
first install allure.
allure-pytest         2.6.0     
allure-python-commons 2.6.0  

then if you unable to genrated the reports then follow below steps..
step -1 (using pytest)
pytest test_parameterDemo.py --alluredir=path where you want to save reports.

step -2 
allure serve report_path

if still it is showing allure is not command (blah -blah)

then install allure using npm plugin with below command
npm install -g allure-commandline --save-dev

then again follow step-2 then one server will start and you can able to see allure reports.

**Comment by senthilkumar369** [comment]
Hi All,

How do the stake holders view the report. it is being created for them right, not for dev and testers alone. I mean , all stakeholder cant ask them to install allure on theirs pc to view it. Note Jenkins or other CI not used. Could you please give me some idea to open the report in offline? . Browser keeps updating that stops viewing the allure reports.
